//! Core data types for JEPA.

use burn::tensor::{backend::Backend, Tensor};

/// A representation produced by an encoder.
///
/// Wraps a tensor with semantic meaning. A representation is the compressed,
/// abstract form of an input that captures essential features while discarding
/// irrelevant details.
///
/// Shape: `[batch_size, sequence_length, embed_dim]`
#[derive(Debug, Clone)]
pub struct Representation<B: Backend> {
    /// The embedding tensor.
    pub embeddings: Tensor<B, 3>,
}

impl<B: Backend> Representation<B> {
    /// Create a new representation from a tensor.
    pub fn new(embeddings: Tensor<B, 3>) -> Self {
        Self { embeddings }
    }

    /// Get the batch size.
    pub fn batch_size(&self) -> usize {
        self.embeddings.dims()[0]
    }

    /// Get the sequence length (number of tokens/patches).
    pub fn seq_len(&self) -> usize {
        self.embeddings.dims()[1]
    }

    /// Get the embedding dimension.
    pub fn embed_dim(&self) -> usize {
        self.embeddings.dims()[2]
    }
}

/// Energy scalar measuring compatibility between two representations.
///
/// Lower energy indicates higher compatibility (better prediction).
/// This is the core quantity that JEPA training minimizes.
#[derive(Debug, Clone)]
pub struct Energy<B: Backend> {
    /// The energy value. Shape: scalar `[1]`
    pub value: Tensor<B, 1>,
}

/// Specification of which tokens are context (visible) vs target (hidden).
///
/// Generated by a [`MaskingStrategy`] and consumed by the training loop
/// to split the input into context and prediction targets.
#[derive(Debug, Clone)]
pub struct MaskSpec {
    /// Indices of context (visible) tokens.
    pub context_indices: Vec<usize>,
    /// Indices of target (hidden) tokens to predict.
    pub target_indices: Vec<usize>,
    /// Total number of tokens in the input.
    pub total_tokens: usize,
}

impl MaskSpec {
    /// Verify that the mask is well-formed.
    pub fn validate(&self) -> Result<(), MaskError> {
        use std::collections::HashSet;

        // No empty partitions
        if self.context_indices.is_empty() {
            return Err(MaskError::EmptyContext);
        }
        if self.target_indices.is_empty() {
            return Err(MaskError::EmptyTarget);
        }

        // No duplicates
        let mut seen = HashSet::with_capacity(self.total_tokens);
        for &idx in self.context_indices.iter().chain(self.target_indices.iter()) {
            if idx >= self.total_tokens {
                return Err(MaskError::IndexOutOfBounds { index: idx, total: self.total_tokens });
            }
            if !seen.insert(idx) {
                return Err(MaskError::DuplicateIndex(idx));
            }
        }

        Ok(())
    }

    /// Fraction of tokens masked as targets.
    pub fn mask_ratio(&self) -> f64 {
        self.target_indices.len() as f64 / self.total_tokens as f64
    }
}

/// Errors related to mask validation.
#[derive(Debug, thiserror::Error)]
pub enum MaskError {
    #[error("context indices are empty, need at least one visible token")]
    EmptyContext,
    #[error("target indices are empty, need at least one token to predict")]
    EmptyTarget,
    #[error("index {index} is out of bounds for {total} total tokens")]
    IndexOutOfBounds { index: usize, total: usize },
    #[error("duplicate index {0} found in mask")]
    DuplicateIndex(usize),
}

/// Shape of the input to a masking strategy.
#[derive(Debug, Clone)]
pub enum InputShape {
    /// 2D grid of patches (for images).
    Image {
        /// Number of patch rows.
        height: usize,
        /// Number of patch columns.
        width: usize,
    },
    /// 3D grid of tubelets (for video).
    Video {
        /// Number of temporal positions.
        frames: usize,
        /// Number of patch rows per frame.
        height: usize,
        /// Number of patch columns per frame.
        width: usize,
    },
}

impl InputShape {
    /// Total number of tokens.
    pub fn total_tokens(&self) -> usize {
        match self {
            InputShape::Image { height, width } => height * width,
            InputShape::Video { frames, height, width } => frames * height * width,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_mask_spec_validate_valid() {
        let mask = MaskSpec {
            context_indices: vec![0, 1, 2],
            target_indices: vec![3, 4, 5],
            total_tokens: 6,
        };
        assert!(mask.validate().is_ok());
    }

    #[test]
    fn test_mask_spec_validate_empty_context() {
        let mask = MaskSpec {
            context_indices: vec![],
            target_indices: vec![0, 1],
            total_tokens: 2,
        };
        assert!(matches!(mask.validate(), Err(MaskError::EmptyContext)));
    }

    #[test]
    fn test_mask_spec_validate_duplicate() {
        let mask = MaskSpec {
            context_indices: vec![0, 1],
            target_indices: vec![1, 2],
            total_tokens: 3,
        };
        assert!(matches!(mask.validate(), Err(MaskError::DuplicateIndex(1))));
    }

    #[test]
    fn test_mask_spec_validate_out_of_bounds() {
        let mask = MaskSpec {
            context_indices: vec![0],
            target_indices: vec![5],
            total_tokens: 3,
        };
        assert!(matches!(mask.validate(), Err(MaskError::IndexOutOfBounds { .. })));
    }

    #[test]
    fn test_mask_ratio() {
        let mask = MaskSpec {
            context_indices: vec![0, 1, 2, 3],
            target_indices: vec![4, 5],
            total_tokens: 6,
        };
        assert!((mask.mask_ratio() - 1.0 / 3.0).abs() < 1e-10);
    }

    #[test]
    fn test_input_shape_total_tokens() {
        assert_eq!(InputShape::Image { height: 14, width: 14 }.total_tokens(), 196);
        assert_eq!(InputShape::Video { frames: 8, height: 14, width: 14 }.total_tokens(), 1568);
    }
}
